### ISSUE TITLE
[REQ] Cvar default hidden

### ISSUE THREAD

**Issue by trollollol123** [it-killer/CSGO-Hide-teammates#1]
Hi!

I would like to make a request. I would like that the default value for hidden is ON when players join the server. Could be decided with a cvar.  :)

**Comment by IT-KiLLER** [comment]
Hey 
Thank you for your request.
I've updated the plugin with it. 👍 
Check out version 1.1.2

**Comment by trollollol123** [comment]
cool nice! :)
