### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Truyn** [it-killer/CSGO-Hide-teammates#3]
L 03/24/2022 - 09:32:05: Info (map "ze_licciana_escape_zrgbr_b3") (file "/home/container/csgo/addons/sourcemod/logs/errors_20220324.log")
L 03/24/2022 - 09:32:05: [SM] Exception reported: Invalid timer handle 6db005a0 (error 1)
L 03/24/2022 - 09:32:05: [SM] Blaming: hide_teammates.smx
L 03/24/2022 - 09:32:05: [SM] Call stack trace:
L 03/24/2022 - 09:32:05: [SM]   [0] KillTimer
L 03/24/2022 - 09:32:05: [SM]   [1] Line 130, E:\PLUGINS CSGO\Plugins\compilator\addons\sourcemod\scripting\hide_teammates.sp::OnConVarChange
L 03/24/2022 - 09:32:05: [SM]   [3] ConVar.SetString
L 03/24/2022 - 09:32:05: [SM]   [4] Line 333, /home/builds/sourcemod/linux-1.10/build/plugins/basecommands.sp::Command_Cvar
L 03/24/2022 - 09:38:28: Error log file session closed.

**Comment by azalty** [comment]
Fix:

Replace lines 128-131:

```
		if(g_timer != INVALID_HANDLE)
		{
			KillTimer(g_timer);
		}
```

To just this:
```
		delete g_timer;
```

If you don't know how to compile, I'll soon do a Pull Request and compile it myself for you.

**Comment by azalty** [comment]
You can get my 2 patches here since the author doesn't seem to be active anymore: https://github.com/azalty/CSGO-Hide-teammates/tree/master-all-patches

**Comment by azalty** [comment]
You should consider letting this issue open since the bug isn't fixed in the official repo @Truyn
